version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: evolution-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: evolution_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - evolution-network

  evolution-api:
    build: .
    container_name: evolution-api
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      # Database Configuration
      DATABASE_PROVIDER: postgresql
      DATABASE_CONNECTION_URI: postgresql://postgres:${POSTGRES_PASSWORD:-PASSWORD}@postgres:5432/evolution_api
      
      # Server Configuration
      SERVER_TYPE: http
      SERVER_PORT: 8080
      SERVER_URL: ${SERVER_URL:-http://localhost:8080}
      
      # CORS Configuration
      CORS_ORIGIN: "*"
      CORS_METHODS: "GET,POST,PUT,DELETE"
      CORS_CREDENTIALS: "true"
      
      # Security
      JWT_SECRET: ${JWT_SECRET:-your-secret-key-here}
      JWT_EXPIRES_IN: 7d
      
      # WhatsApp Configuration
      WHATSAPP_DEFAULT_ANSWER: "Hola! Estoy usando Evolution API"
      WHATSAPP_GROUP_LIMIT: 256
      
      # Logging
      LOG_LEVEL: INFO
      LOG_COLOR: true
      
      # Redis (opcional)
      REDIS_ENABLED: false
      
      # Database Save Settings
      DATABASE_SAVE_DATA_INSTANCE: true
      DATABASE_SAVE_DATA_NEW_MESSAGE: true
      DATABASE_SAVE_MESSAGE_UPDATE: true
      DATABASE_SAVE_DATA_CONTACTS: true
      DATABASE_SAVE_DATA_CHATS: true
      DATABASE_SAVE_DATA_LABELS: true
      DATABASE_SAVE_DATA_HISTORIC: true
      DATABASE_SAVE_IS_ON_WHATSAPP: true
      DATABASE_SAVE_IS_ON_WHATSAPP_DAYS: 7
      DATABASE_DELETE_MESSAGE: true
      
      # Webhook
      WEBHOOK_BY_EVENTS: false
      WEBHOOK_GLOBAL: ${WEBHOOK_GLOBAL:-}
      
      # File Upload
      FILE_UPLOAD_MAX_SIZE: 100MB
      FILE_UPLOAD_PATH: ./uploads
      
    ports:
      - "8080:8080"
    volumes:
      - evolution_data:/evolution/uploads
      - evolution_sessions:/evolution/sessions
    networks:
      - evolution-network

volumes:
  postgres_data:
    driver: local
  evolution_data:
    driver: local
  evolution_sessions:
    driver: local

networks:
  evolution-network:
    driver: bridge
